name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  http: ^0.13.4
  path_provider: ^2.0.8
  provider: ^6.0.2
  sqflite: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

flutter:
  uses-material-design: true

  assets:
    - assets/
