name: search
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg