name: Flutter CI

# This workflow is triggered on pushes or pull requests to the repository

on:
  push:
    branches:
    - main
  
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Setup the flutter environtment
    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    # Get flutter dependencies
    - name: Restore packages
      run: flutter pub get

    # Check for any formatting issue in the code
    - name: Check formatting issue
      run: flutter format --set-exit-if-changed .

    # Statically analyze the Dart code for any errors.
    - name: Analyze
      run: flutter analyze .

    # Run widget tests for our flutter project.
    - name: Run tests
      run: flutter test --coverage

    # Upload coverage to codecov
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/lcov.info
